# Generated by Django 3.0.4 on 2020-03-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200329_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='profil_pic',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
